### ISSUE TITLE
eval: Symbol’s function definition is void: jk-org-kwd

### ISSUE THREAD

**Issue by incandescentman** [tsdye/tufte-org-mode#1]
Hi, I get `eval: Symbol’s function definition is void: jk-org-kwd` when I do an export. 

GNU Emacs 25.1.1 (x86_64-apple-darwin15.5.0, Carbon Version 157 AppKit 1404.47), Org mode version 9.0.5

**Comment by tsdye** [comment]
The function jk-org-kwd is defined in Setup/Document source code/Access keyword values/jk-keywords, and is loaded with the call to  # eval: (org-sbe "jk-keywords") in the Local variables.

Make certain your export document contains the jk-keywords source code block and the # eval line in the Local Variables, and that the Local Variables were loaded despite the security risk.

**Comment by incandescentman** [comment]
That worked, thanks!
