### ISSUE TITLE
LaTeX code appearing in output

### ISSUE THREAD

**Issue by incandescentman** [tsdye/tufte-org-mode#2]
Several sections of `tufte-latex.org` aren't being exported properly:

```
#+begin_example
[This is a new thought](latex:newthought) at the start 
of another paragraph, introduced with an Org mode link,
and containing a footnote.[fn:2]

,* Footnotes
,#+attr_latex: :offset 24pt
[fn:2] This footnote is shifted down.
#+end_example

``` 

Also, some text on the PDF output overlaps on to of other text. See attached output file. Thanks for any help!

[tufte-handout.pdf](https://github.com/tsdye/tufte-org-mode/files/978015/tufte-handout.pdf)

[tufte-handout.org.txt](https://github.com/tsdye/tufte-org-mode/files/978018/tufte-handout.org.txt)

**Comment by incandescentman** [comment]
I figured out that the code is from the examples. I deleted the examples and it is fixed.

**Comment by tsdye** [comment]
Closed.  Thanks!
