### ISSUE TITLE
Remove confirmation of Evaluate this emacs-lisp code block?

### ISSUE THREAD

**Issue by incandescentman** [tsdye/tufte-org-mode#3]
How can I set it so that it doesn't prompt me to confirm `Evaluate this emacs-lisp code block?` (1) every time I open a tufte-org-mode file, and (2) every time I do an org-export? I am willing to accept any security risks this may pose.

**Comment by tsdye** [comment]
See org-confirm-babel-evaluate.

hth,
Tom

Jay Dixit writes:

> How can I set it so that it doesn't prompt me to confirm Evaluate this emacs-lisp code block? every time I do an
> org-export? I am willing to accept any security risk this may pose.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.


--
Thomas S. Dye
http://www.tsdye.com

**Comment by incandescentman** [comment]
That worked, thanks!
