### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by agenbite** [tsdye/tufte-org-mode#9]
Sorry for the vague heading, but while I've been enjoying this mode a lot, and I'm very thankful for its existence, it is still a mystery for me.

Say I have an org file which I've been converting to pdf with the standard article latex class, and I decide I want to have it in Tufte's ultracool format. At first, I thought I could just change the latex class in my code to tufte-handout and that it would just work. However, I see that there's much more to it since in the template tufte-latex.org there's a ton of emacs code that needs to be run prior to any compilation. I'm confused, is this an emacs mode, an emacs package?

So I wonder if the idea is that I should directly modify the template and copy-paste my org document there. This seems weird since the template covers also the book format, which I don't need at the moment. What is the intended use of this mode? Should I start every document inside a new copy of the template? Would it be possible to have a single file to import into my org file, or maybe an emacs package that I could just install once and for all?

Thanks again for the hard work!

**Comment by tsdye** [comment]
Aloha inwit,

inwit ***@***.***> writes:

> Sorry for the vague heading, but while I've been enjoying this 
> mode a lot, and I'm very thankful for its existence, it is still 
> a mystery for me.
>
> Say I have an org file which I've been converting to pdf with 
> the standard article latex class, and I decide I want to have it 
> in Tufte's ultracool format. At first, I thought I could
> just change the latex class in my code to tufte-handout and that 
> it would just work. However, I see that there's much more to it 
> since in the template tufte-latex.org there's a ton of
> emacs code that needs to be run prior to any compilation. I'm 
> confused, is this an emacs mode, an emacs package?
>
> So I wonder if the idea is that I should directly modify the 
> template and copy-paste my org document there. This seems weird 
> since the template covers also the book format, which I
> don't need at the moment. What is the intended use of this mode? 
> Should I start every document inside a new copy of the template? 
> Would it be possible to have a single file to import
> into my org file, or maybe an emacs package that I could just 
> install once and for all?
>
> Thanks again for the hard work!

This was meant as a patch to Org mode.  Nevertheless, it has been 
overtaken by Org mode development, which now makes it possible to 
use tufte-latex out of the box.  I have it on my to-do list to 
write up a how-to description.  When I've done this, I'll 
deprecate tufte-org-mode and add a link to the how-to.

All the best,
Tom

-- 
Thomas S. Dye
https://tsdye.online/tsdye

**Comment by agenbite** [comment]
Hi, Tom! Thanks for your prompt reply! It'll be great if you can write that how-to some day, because there's not a lot of info about this. In the meantime, maybe you could add a quick note to this repo warning that the proper approach is now to use tufte-latex directly from orgmode, instead of tinkering with your template. It could save some time to other gullible individuals like me... :D Thanks again!
